config/routes.rb
Rails.application.routes.draw do

  root to: 'rms_main#index'
  resources :rms_requests
  resources :rms_clients 
  
  get  '/login', to: 'rms_login#new'
  post '/login', to: 'rms_login#create'
  delete '/logout', to: 'rms_login#destroy'
  
end

app/models/rms_client.rb
class RmsClient < ApplicationRecord

  validates :name, length: { maximum: 255 }, presence: true, uniqueness: true
  validates :tel, length: { maximum: 13 } 
  validates :email, length: { maximum: 255 } 
  validates :address1, length: { maximum: 255 } 
  validates :address2, length: { maximum: 255 } 
  validates :address3, length: { maximum: 255 } 
  
  # 検索対象のカラム ※デフォルトは全て
  def self.ransackable_attributes(auth_object = nil)
    %w[name]
  end  
end

app/controllers/rms_clients_controller.rb
class RmsClientsController < ApplicationController
  before_action :set_rms_client, only: [:show, :edit, :update, :destroy]

  helper_method :common_get_week, :common_convert_nbsp
  helper_method :rms_get_expense_total, :rms_get_types_from_id, :rms_get_requests_total_data  

  # GET /clients
  def index
    @q = RmsClient.order(name: "ASC")
    
    # 空白除去 ※全角空白を半角空白に変換含む
    if params[:q].present?
      params[:q][:name_cont]= common_trim(params[:q][:name_cont])
    end  
    
    @q = @q.ransack(params[:q])  
    @rms_clients = @q.result(distinct: true).page(params[:page]).per(25)  
    
    # ID/総売上/総経費/ご依頼件数/最終ご依頼日
    sql = " SELECT "+
          "   client_id, " +
          "   SUM(sales) AS sales_total," +
          "   SUM(expense1+expense2+expense3+expense4+expense5+expense6+expense7+expense8+expense9+expense10) AS expense_total," +
          "   COUNT(client_id) AS cnt," +
          "   MAX(STR_TO_DATE(yyyy,'%Y') + STR_TO_DATE(mm,'%m')+ STR_TO_DATE(dd,'%d')) AS lastday" +
          " FROM rms_requests" +
          " GROUP BY client_id" 
    @rms_requests_total_data = RmsRequest.find_by_sql(sql)  
  end

  # GET /clients/1
  def show
     # コンボボックスデータ
     rms_get_types_combobox()
     
     # SQLで日付を生成してソートする - 過去の履歴用
     sql = "SELECT *, (STR_TO_DATE(yyyy,'%Y') + STR_TO_DATE(mm,'%m')+ STR_TO_DATE(dd,'%d')) as day" +
           " FROM rms_requests" +
           " WHERE client_id =?" +
           " ORDER BY day DESC"           
     @rms_requests = RmsRequest.find_by_sql([sql,params[:id]])      
  end

  # GET /clients/new
  def new
    @rms_client = RmsClient.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @rms_client = RmsClient.new(rms_client_params) 

    # 文字列の整形
    rms_client_formatting()
     
    respond_to do |format|
      if @rms_client.save
        format.html { redirect_to rms_clients_path, notice: '登録しました。' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /clients/1
  def update      
    respond_to do |format|
      if @rms_client.update(rms_client_params)
        format.html { redirect_to rms_clients_path, notice: '更新しました。' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /clients/1
  def destroy
    
    # 顧客に紐づくご依頼も削除する
    ActiveRecord::Base.transaction do
       @rms_client.destroy!
       requests = RmsRequest.where(client_id: @rms_client.id)       
       requests.each { |a|
         a.destroy! 
       } 
       redirect_to rms_clients_path, alert: "「#{@rms_client.name}」さんを削除しました。"
    end
  end

  
  private
    def set_rms_client
      @rms_client = RmsClient.find(params[:id])
      
      # 文字列の整形
      rms_client_formatting()                                             
    end

    def rms_client_params
      params.require(:rms_client).permit(:name, :tel, :email, :address1, :address2, :address3, :info)
    end    
  
    # 文字列の整形
    def rms_client_formatting()    
      # 空白除去 ※全角空白を半角空白に変換含む
      @rms_client.name = common_trim(@rms_client.name)  
      @rms_client.tel = common_trim(@rms_client.tel) 
      @rms_client.email = common_trim(@rms_client.email) 
      @rms_client.address1 = common_trim(@rms_client.address1) 
      @rms_client.address2 = common_trim(@rms_client.address2) 
      @rms_client.address3 = common_trim(@rms_client.address3) 
      @rms_client.info = common_trim(@rms_client.info)  
    end    
end

app/helpers/rms_clients_helper.rb
module RmsClientsHelper
end

app/views/rms_clients/_form.html.slim
= form_with model: @rms_client, local: true do |f|
  - if @rms_client.errors.any?
    #error_explanation.text-danger
      ul
        - @rms_client.errors.full_messages.each do |message|
          li = message

  .form-group
    = raw '<label for="rms_client_name">' + RmsClient.human_attribute_name(:name) +'</label>'
    = raw '&nbsp;&nbsp;' + '<span class="badge badge-success" style="font-size:16px;"> 必須 </span>'
    = f.text_field :name, class: 'form-control', id: 'rms_client_name', placeholder: "山田太郎"
  .form-group
    = f.label :tel
    = f.text_field :tel, class: 'form-control', id: 'rms_client_tel', placeholder: "0120-01-2345"
  .form-group
    = f.label :email
    = f.email_field :email, class: 'form-control', id: 'rms_client_email' , placeholder: "info@example.com"   
  .form-group
    = f.label :address1
    = f.text_field :address1, class: 'form-control', id: 'rms_client_address1' , placeholder: "東京都"      
  .form-group
    = f.label :address2
    = f.text_field :address2, class: 'form-control', id: 'rms_client_address2' , placeholder: "千代田区"     
  .form-group
    = f.label :address3
    = f.text_field :address3, class: 'form-control', id: 'rms_client_address3'  , placeholder: "千代田1-1"     
  .form-group
    = f.label :info
    = f.text_area :info, rows: 5, class: 'form-control', id: 'rms_client_info'  , placeholder: "ここに基本的な情報を記述します。"          

  = f.submit yield(:submit) , class: 'btn btn-primary'  

app/views/rms_clients/edit.html.slim
- provide(:title, '顧客 - 編集')
- provide(:submit, '更新する')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("顧客", rms_clients_path)     
    li.breadcrumb-item.active aria-current="page" = '編集'
    
p
h1 顧客情報の編集
p

== render 'form'


br
br

= raw '<a href="#" onClick="history.back(); return false;">戻る</a>'
p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("顧客", rms_clients_path)     
    li.breadcrumb-item.active aria-current="page" = '編集'
    
p    

app/views/rms_clients/index.html.slim
- provide(:title, '顧客')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item.active aria-current="page" = '顧客'
    
p
h1 顧客
p

= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control', placeholder: "検索したい名前を入力します。"   
  .form-group
    = f.submit class: 'btn btn-outline-primary'


= link_to '顧客の新規登録', new_rms_client_path,class: 'btn btn-primary'  
p

div.pc    
  table.table.table-hover
    thead.thead-default
      tr
        th style="width:170px;"  = "一覧"
        th
        th

    tbody
      - @rms_clients.each_with_index do |client,i|
        - obj = rms_get_requests_total_data(client.id)
        tr
          td  
           span = link_to(client.name, client)
           span style="font-size:90%" = " さん"         
          td 
            div            
              - if client.address1.present?
                span.pc
                  span.text-secondary = " <" + client.address1 + ">"
              
            - if obj["cnt"] > 0
              div = "ご依頼 " + obj["cnt"].to_s()  +"件" + " 最終ご依頼日 " + Time.parse(obj["lastday"].to_s()).strftime("%Y年%m月%d日")
            - else
              div = "ご依頼 " + obj["cnt"].to_s()  +"件"
            - if obj["cnt"] > 0            
              div.text-success = "合計：売上 " + obj["sales_total"].to_s(:delimited) + "円"  + \
                                 " 経費 " + obj["expense_total"].to_s(:delimited) + "円"  + \
                                 " 営業利益 " + (obj["sales_total"] - obj["expense_total"]).to_s(:delimited) + "円"    
          td
            span = link_to '編集', edit_rms_client_path(client), class: 'btn btn-primary' 
            span = raw "&nbsp;&nbsp;&nbsp;"
            span = link_to '削除', client, data: { confirm: "\n#{client.name} さんを削除します。\nご依頼の履歴がある場合は同時に削除されます。\nよろしいですか？" }, method: :delete, class: 'btn btn-danger' 

div.sp    
  table.table.table-hover
    thead.thead-default
      tr
        th = "一覧"
    tbody
      - @rms_clients.each_with_index do |client,i|
        - obj = rms_get_requests_total_data(client.id)
        tr
          td 
            div    
              span = link_to(client.name, client)
              span style="font-size:90%" = " さん"                       
              - if obj["cnt"] > 0
                div = "ご依頼 " + obj["cnt"].to_s()  +"件" + " 最終ご依頼日 " + Time.parse(obj["lastday"].to_s()).strftime("%Y年%m月%d日")
              - else
                div = "ご依頼 " + obj["cnt"].to_s()  +"件"
              - if obj["cnt"] > 0            
                div.text-success = "合計：売上 " + obj["sales_total"].to_s(:delimited) + "円"  + \
                                   " 経費 " + obj["expense_total"].to_s(:delimited) + "円"  + \
                                   " 営業利益 " + (obj["sales_total"] - obj["expense_total"]).to_s(:delimited) + "円"    
p

/ ページネーション
.mb-3
  = paginate @rms_clients
  = page_entries_info @rms_clients
  
p  

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item.active aria-current="page" = '顧客'

p      

app/views/rms_clients/new.html.slim
- provide(:title, '顧客 - 新規登録')
- provide(:submit, '登録する')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("顧客", rms_clients_path)     
    li.breadcrumb-item.active aria-current="page" = '新規作成'
    
p
h1 新規登録 - 顧客
p

== render 'form'

br
br
= raw '<a href="#" onClick="history.back(); return false;">戻る</a>'
p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("顧客", rms_clients_path)     
    li.breadcrumb-item.active aria-current="page" = '新規作成'

p    

app/views/rms_clients/show.html.slim
- provide(:title, '顧客 - 表示')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("顧客", rms_clients_path)     
    li.breadcrumb-item.active aria-current="page" = '表示'
    
p
h2 
  span = @rms_client.name
  span style="font-size:70%"= " さん"
p

= link_to 'ご依頼の新規登録', new_rms_request_path(client_id: @rms_client.id),class: 'btn btn-primary'  

.mb-3
table.table.table-hover
  tr
    th style = "width:150px;" =RmsClient.human_attribute_name(:tel)
    td = @rms_client.tel     
  tr
    th =RmsClient.human_attribute_name(:email)
    td = @rms_client.email     
  tr
    th =RmsClient.human_attribute_name(:address1)
    td = @rms_client.address1     
  tr
    th =RmsClient.human_attribute_name(:address2)
    td = @rms_client.address2     
  tr
    th =RmsClient.human_attribute_name(:address3)
    td = @rms_client.address3     
  tr
    th =RmsClient.human_attribute_name(:info)
    td = raw common_convert_nbsp(auto_link(simple_format(h(@rms_client.info), {}, sanitize: false, wrapper_tag: "p")))

p
h3 過去の履歴
p
- sales_total = 0
- expense_total = 0

- @rms_requests.each_with_index do |request,i|
  / 経費の合計
  - expense = rms_get_expense_total(request)
  / トータル
  - sales_total += request.sales 
  - expense_total += expense
  / 年月日
  - yyyymmdd = request.yyyy.to_s + "年" + sprintf("%02d月",request.mm) + sprintf("%02d日",request.dd) + "(" + common_get_week(request.yyyy,request.mm,request.dd) + ") "
  table.table.table-hover
    tr
      td  
        div
          span
            = link_to(yyyymmdd,rms_request_path(request.id))
            span.text-secondary = " <" + rms_get_types_from_id(request.types) +">"
          br
          =  request.title
          br
          span.text-success = "売上 " + request.sales.to_s(:delimited) + "円"  + \
                              " 経費 " + expense.to_s(:delimited) + "円"  + \
                              " 営業利益 " + (request.sales - expense).to_s(:delimited) + "円"    
p

p
h3 合計
p
div = "売上 " + sales_total.to_s(:delimited) + "円"  + \
      " 経費 " + expense_total.to_s(:delimited) + "円"  + \
      " 営業利益 " + (sales_total - expense_total).to_s(:delimited) + "円"  

br

div
  div.float-right
    span = link_to '編集', edit_rms_client_path(@rms_client), class: 'btn btn-primary' 
    span = raw "&nbsp;&nbsp;&nbsp;"
    span = link_to '削除', @rms_client, data: { confirm: "\n#{@rms_client.name} さんを削除します。\nご依頼の履歴がある場合は同時に削除されます。\nよろしいですか？" }, method: :delete, class: 'btn btn-danger' 
  div.float-left
    = raw '<a href="#" onClick="history.back(); return false;">戻る</a>'
div.clearfix    
    
p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("顧客", rms_clients_path)     
    li.breadcrumb-item.active aria-current="page" = '表示'
    
p    