config/routes.rb
Rails.application.routes.draw do

  root to: 'rms_main#index'
  resources :rms_requests
  resources :rms_clients 
  
  get  '/login', to: 'rms_login#new'
  post '/login', to: 'rms_login#create'
  delete '/logout', to: 'rms_login#destroy'
  
end

app/models/rms_request.rb
class RmsRequest < ApplicationRecord
  validates :client_id, presence: true
  validates :types,     presence: true
  validates :title,     presence: true, length: { maximum: 255 }   
  validates :yyyy,      presence: true
  validates :mm,        presence: true
  validates :dd,        presence: true
  validates :day_times, presence: true, length: { maximum: 3 }   
    
  validates :yyyy, numericality: { greater_than_or_equal_to: 1989, less_than_or_equal_to: 2099 } , unless: Proc.new { |a| a.yyyy.blank? }
  validates :mm,   numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 12 } , unless: Proc.new { |a| a.mm.blank? } 
  validates :dd,   numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 31 } , unless: Proc.new { |a| a.dd.blank? } 
  
  validates :sales, length: { maximum: 8 }, presence: true 
  validates :expense1, length: { maximum: 8 }, presence: true 
  validates :expense2, length: { maximum: 8 }, presence: true   
  validates :expense3, length: { maximum: 8 }, presence: true 
  validates :expense4, length: { maximum: 8 }, presence: true   
  validates :expense5, length: { maximum: 8 }, presence: true 
  validates :expense6, length: { maximum: 8 }, presence: true   
  validates :expense7, length: { maximum: 8 }, presence: true 
  validates :expense8, length: { maximum: 8 }, presence: true   
  validates :expense9, length: { maximum: 8 }, presence: true 
  validates :expense10, length: { maximum: 8 }, presence: true   
end

app/controllers/rms_requests_controller.rb
class RmsRequestsController < ApplicationController
  before_action :set_rms_request, only: [:show, :edit, :update, :destroy]
  
  before_action :rms_get_clients_combobox, :rms_get_types_combobox
  
  helper_method :common_get_week, :common_convert_nbsp 
  helper_method :rms_get_expense_total, :rms_get_clients_from_id, :rms_get_types_from_id
    
  # GET /requests
  def index
    # SQLで日付を生成してソートする 
    sql = "*, (STR_TO_DATE(yyyy,'%Y') + STR_TO_DATE(mm,'%m')+ STR_TO_DATE(dd,'%d')) as day"
    @q = RmsRequest.select(sql).order(day: "DESC")  
    @rms_requests = @q.page(params[:page]).per(25)  
  end

  # GET /requests/1
  def show
  end

  # GET /requests/new
  def new
    @rms_request = RmsRequest.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  def create
    @rms_request = RmsRequest.new(rms_request_params)

    # 文字列の整形
    rms_request_formatting()    
      
    respond_to do |format|
      if @rms_request.save
        format.html { redirect_to rms_requests_path, notice: '登録しました。' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /requests/1
  def update
    respond_to do |format|
      if @rms_request.update(rms_request_params)
        format.html { redirect_to rms_requests_path, notice: '更新しました。' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /requests/1
  def destroy
    @rms_request.destroy
    respond_to do |format|
      days = @rms_request.yyyy.to_s + "年" + sprintf("%02d月",@rms_request.mm) + sprintf("%02d日",@rms_request.dd) 
      format.html { redirect_to rms_requests_path, alert: '' + days + 'のご依頼を削除しました。' }
    end
  end

  private
    def set_rms_request
      @rms_request = RmsRequest.find(params[:id])
      
      # 文字列の整形
      rms_request_formatting()         
    end

    def rms_request_params
      params.require(:rms_request).permit(:client_id, :title, :types, :yyyy, :mm, :dd, :day_times, :sales, :expense1, :expense2, :expense3, :expense4, :expense5, :expense6, :expense7, :expense8, :expense9, :expense10, :content, :remarks)
    end
    
    # 文字列の整形
    def rms_request_formatting()    
      # 空白除去 ※全角空白を半角空白に変換含む
      @rms_request.title = common_trim(@rms_request.title)  
      @rms_request.content = common_trim(@rms_request.content) 
      @rms_request.remarks = common_trim(@rms_request.remarks) 
    end    
end

app/helpers/rms_requests_helper.rb
module RmsRequestsHelper
end

app/views/rms_requests/_form.html.slim
= form_with model: @rms_request, local: true do |f|
  - if @rms_request.errors.any?
  #error_explanation.text-danger
      ul
        - @rms_request.errors.full_messages.each do |message|
          li = message

  div.alert.alert-primary 1. 基本情報

  .form-group
    = raw '<label for="rms_request_client_id">顧客</label>&nbsp;&nbsp;<span class="badge badge-success" style="font-size:16px;"> 必須 </span>' +"\n"  
    br
    = raw '<select name="rms_request[client_id]" id="rms_request_client_id">' +"\n" 
    = raw '<option value="">選択して下さい。</option>' +"\n" 
    - @rms_clients_list.each do |obj|
      - if (params[:client_id] ==  obj[1].to_s())
        = raw '<option value="' + obj[1].to_s()  +'" selected="selected">' + h(obj[0]) +'</option>' +"\n"    
      - else
        - if (@rms_request.client_id ==  obj[1])
          = raw '<option value="' + obj[1].to_s()  +'" selected="selected">' + h(obj[0]) +'</option>' +"\n"     
        - else
          = raw '<option value="' + obj[1].to_s()  +'">' + h(obj[0]) +'</option>' +"\n"       
        
    = raw '</select>' +"\n" 
    = raw '&nbsp;&nbsp;<input placeholder="名前" id="search_name" type="text" style="width:135px;" />'
    = raw '&nbsp;&nbsp;<button onclick="search_run();return false;">検索</button>'

  / 顧客リストの検索
  = raw '<script>' + "\n"
  = raw 'function search_run(){'  + "\n"
  = raw '' + "\n"
  = raw '  // 空白の除去' + "\n"
  = raw '  var search_name = document.getElementById("search_name");' + "\n"
  = raw '  search_name.value = search_name.value.trim();' + "\n"
  = raw '  if(search_name.value == "") return;    ' + "\n"
  = raw '' + "\n"  
  = raw '  var rms_request_client_id = document.getElementById("rms_request_client_id");'   + "\n"
  = raw '' + "\n"
  = raw '  for (i=0; i<rms_request_client_id.length; i++) {' + "\n"
  = raw '' + "\n"
  = raw '    // 文字列が含まれる場合' + "\n"
  = raw '    if (rms_request_client_id[i].text.indexOf(search_name.value) != -1) {' + "\n"
  = raw '      rms_request_client_id.selectedIndex = i' + "\n"
  = raw '      break;' + "\n"
  = raw '    }' + "\n"
  = raw '  }' + "\n"            
  = raw '}' + "\n"
  = raw '</script>' + "\n"

  .form-group
    = raw '<label for="rms_request_types">' + RmsRequest.human_attribute_name(:types) +'</label>'    
    = raw '&nbsp;&nbsp;' + '<span class="badge badge-success" style="font-size:16px;"> 必須 </span><br>'   
    - if @rms_request.types.present?    
      = f.select :types, options_for_select(@rms_types_list,@rms_request.types),include_blank: '選択して下さい。',id: 'rms_request_types'
    - else
      = f.select :types, options_for_select(@rms_types_list),include_blank: '選択して下さい。',id: 'rms_request_types'
    
  .form-group
    = raw '<label for="rms_request_title">' + RmsRequest.human_attribute_name(:title) +'</label>'    
    = raw '&nbsp;&nbsp;' + '<span class="badge badge-success" style="font-size:16px;"> 必須 </span>'   
    = f.text_field :title, class: 'form-control',  placeholder: "ご依頼のタイトルを一行で入力。",id: 'rms_request_title'
         
  .form-group
    = raw '<label for="rms_request_yyyy">' + RmsRequest.human_attribute_name(:yyyy) +'</label>'    
    = raw '&nbsp;&nbsp;' + '<span class="badge badge-success" style="font-size:16px;"> 必須 </span>'   
    = f.number_field :yyyy, class: 'form-control',  placeholder: "2000",id: 'rms_request_yyyy'
  .form-group
    = raw '<label for="rms_request_mm">' + RmsRequest.human_attribute_name(:mm) +'</label>'    
    = raw '&nbsp;&nbsp;' + '<span class="badge badge-success" style="font-size:16px;"> 必須 </span>'   
    = f.number_field :mm, class: 'form-control', placeholder: "11",id: 'rms_request_mm'
  .form-group
    = raw '<label for="rms_request_dd">' + RmsRequest.human_attribute_name(:dd) +'</label>'    
    = raw '&nbsp;&nbsp;' + '<span class="badge badge-success" style="font-size:16px;"> 必須 </span>'   
    = f.number_field :dd, class: 'form-control', placeholder: "28",id: 'rms_request_dd'
  .field
    = raw '<label for="rms_request_day_times">' + RmsRequest.human_attribute_name(:day_times) +'</label>'    
    = raw '&nbsp;&nbsp;' + '<span class="badge badge-success" style="font-size:16px;"> 必須 </span>'
    = f.number_field :day_times,  class: 'form-control',placeholder: "電話相談は分単位。それ以外は日数。(例) 1泊2日は2とする。" ,id: 'rms_request_day_times' 
  
  p
  div.alert.alert-primary 2. 売上 (円単位)
  p
  
  .form-group
    = f.label :sales 
    = f.number_field :sales, class: 'form-control', id: 'rms_request_sales'

  p
  div.alert.alert-primary 3. 経費 (円単位)
  p
  
  .form-group
    = f.label :expense1 
    = f.number_field :expense1, class: 'form-control', id: 'rms_request_expense1'
  .form-group
    = f.label :expense2 
    = f.number_field :expense2, class: 'form-control', id: 'rms_request_expense2'      
  .form-group
    = f.label :expense3 
    = f.number_field :expense3, class: 'form-control', id: 'rms_request_expense3'      
  .form-group
    = f.label :expense4 
    = f.number_field :expense4, class: 'form-control', id: 'rms_request_expense4'      
  .form-group
    = f.label :expense5 
    = f.number_field :expense5, class: 'form-control', id: 'rms_request_expense5'            
  .form-group
    = f.label :expense6 
    = f.number_field :expense6, class: 'form-control', id: 'rms_request_expense6'
  .form-group
    = f.label :expense7
    = f.number_field :expense7, class: 'form-control', id: 'rms_request_expense7'      
  .form-group
    = f.label :expense8 
    = f.number_field :expense8, class: 'form-control', id: 'rms_request_expense8'      
  .form-group
    = f.label :expense9 
    = f.number_field :expense9, class: 'form-control', id: 'rms_request_expense9'      
  .form-group
    = f.label :expense10 
    = f.number_field :expense10, class: 'form-control', id: 'rms_request_expense10' 

  p
  div.alert.alert-primary 4. ご依頼内容
  p
  
  .form-group
    = f.label :content
    = f.text_area :content, rows: 10, class: 'form-control', id: 'rms_request_content'  , placeholder: "ここにご依頼の内容を記述します。"  
     
  p
  div.alert.alert-primary 5. 備考
  p
       
  .form-group
    = f.label :remarks
    = f.text_area :remarks, rows: 5, class: 'form-control', id: 'rms_request_remarks'  , placeholder: "ここに備考を記述します。"
  
  br  
  = f.submit yield(:submit), class: 'btn btn-primary'  

app/views/rms_requests/edit.html.slim
- provide(:title, 'ご依頼 - 編集')
- provide(:submit, '更新する')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("ご依頼", rms_requests_path)     
    li.breadcrumb-item.active aria-current="page" = '編集'
    
p
h1 ご依頼の編集
p

== render 'form'

br
br

= raw '<a href="#" onClick="history.back(); return false;">戻る</a>'
p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("ご依頼", rms_requests_path)     
    li.breadcrumb-item.active aria-current="page" = '編集'
    
p    

app/views/rms_requests/index.html.slim
- provide(:title, ' ご依頼')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item.active aria-current="page" = 'ご依頼'
    
p
h1 ご依頼
p

= link_to 'ご依頼の新規登録', new_rms_request_path,class: 'btn btn-primary'  
p
    
div.pc
  table.table.table-hover
    thead.thead-default
      tr
        th style="width:180px;" = "一覧"
        th
        th

    tbody
      - @rms_requests.each do |request|
        / 経費の合計
        - expense = rms_get_expense_total(request)    
        tr
          td = link_to(request.yyyy.to_s + "年" + sprintf("%02d月",request.mm) + sprintf("%02d日",request.dd) +  \ 
                "(" + common_get_week(request.yyyy,request.mm,request.dd) + ")", request) + " "
          td 
            div
              span.text-secondary = rms_get_clients_from_id(request.client_id)
              span.text-secondary style="font-size:90%"  =  " さん" 
              span.text-secondary = " <" +rms_get_types_from_id(request.types) +">"                                    
                                     
            div = request.title  
            div.text-success         
              = "売上 " + request.sales.to_s(:delimited) + "円"  + \
               " 経費 " + expense.to_s(:delimited) + "円"  + \
               " 営業利益 " + (request.sales - expense).to_s(:delimited) + "円"  

          td
            span = link_to '編集', edit_rms_request_path(request), class: 'btn btn-primary' 
            span = raw "&nbsp;&nbsp;&nbsp;"
            - days = Time.parse(request.day.to_s()).strftime("%Y年%m月%d日")
            span = link_to '削除', request, data: { confirm: "\n#{days}\n#{request.title}\nのご依頼を削除します。よろしいですか？" }, method: :delete, class: 'btn btn-danger'  

            
div.sp
  table.table.table-hover
    thead.thead-default
      tr
        th = "一覧"

    tbody
      - @rms_requests.each do |request|
        / 経費の合計
        - expense = rms_get_expense_total(request)    
        tr
          td 
            div
              span = link_to(request.yyyy.to_s + "年" + sprintf("%02d月",request.mm) + sprintf("%02d日",request.dd) +  \
                     "(" + common_get_week(request.yyyy,request.mm,request.dd) + ")", request)
              br       
              span.text-secondary = rms_get_clients_from_id(request.client_id)
              span.text-secondary style="font-size:90%"  =  " さん" 
              span.text-secondary = " <" +rms_get_types_from_id(request.types) +">"                                    
                                     
            div = request.title  
            div.text-success         
              = "売上 " + request.sales.to_s(:delimited) + "円"  + \
               " 経費 " + expense.to_s(:delimited) + "円"  + \
               " 営業利益 " + (request.sales - expense).to_s(:delimited) + "円"  

p

/ ページネーション
.mb-3
  = paginate @rms_requests
  = page_entries_info @rms_requests

p  

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item.active aria-current="page" = 'ご依頼'
    
p    

app/views/rms_requests/new.html.slim
- provide(:title, 'ご依頼 - 新規登録')
- provide(:submit, '登録する')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("ご依頼", rms_requests_path)     
    li.breadcrumb-item.active aria-current="page" = '新規作成'
    
p
h1 新規登録 - ご依頼
p

== render 'form'

br
br
= raw '<a href="#" onClick="history.back(); return false;">戻る</a>'
p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("ご依頼", rms_requests_path)     
    li.breadcrumb-item.active aria-current="page" = '新規作成'
    
p    

app/views/rms_requests/show.html.slim
- provide(:title, '顧客 - 表示')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("ご依頼", rms_requests_path)     
    li.breadcrumb-item.active aria-current="page" = '表示'

p
h2 
  = @rms_request.yyyy.to_s + "年" + sprintf("%02d月",@rms_request.mm) + sprintf("%02d日",@rms_request.dd) + \
    "(" + common_get_week(@rms_request.yyyy,@rms_request.mm,@rms_request.dd) + ")" 
  br  
  = @rms_request.title
p

/ 経費の合計
- expense = rms_get_expense_total(@rms_request)

div.text-success = "売上 " + @rms_request.sales.to_s(:delimited) + "円"  + \
     " 経費 " + expense.to_s(:delimited) + "円"  + \
     " 営業利益 " + (@rms_request.sales - expense).to_s(:delimited) + "円"  


.mb-3
table.table.table-hover
  tr
    th style = "width:150px;" = RmsRequest.human_attribute_name(:client_id)
    td = link_to rms_get_clients_from_id(@rms_request.client_id),   rms_client_path(@rms_request.client_id)   
  tr
    th =RmsRequest.human_attribute_name(:types)
    td = rms_get_types_from_id(@rms_request.types)    
  tr
    th =RmsRequest.human_attribute_name(:day_times)
    - if @rms_request.types == 2
      td = @rms_request.day_times.to_s + "分"       
    - else  
      td = @rms_request.day_times.to_s + "日"       
  tr
    th =RmsRequest.human_attribute_name(:sales)
    td = @rms_request.sales.to_s(:delimited) + "円"       
  tr
    th =RmsRequest.human_attribute_name(:expense1)
    td = @rms_request.expense1.to_s(:delimited) + "円"        
  tr
    th =RmsRequest.human_attribute_name(:expense2)
    td = @rms_request.expense2.to_s(:delimited)  + "円"       
  tr
    th =RmsRequest.human_attribute_name(:expense3)
    td = @rms_request.expense3.to_s(:delimited)  + "円"       
  tr
    th =RmsRequest.human_attribute_name(:expense4)
    td = @rms_request.expense4.to_s(:delimited) + "円"        
  tr
    th =RmsRequest.human_attribute_name(:expense5)
    td = @rms_request.expense5.to_s(:delimited)  + "円"       
  tr
    th =RmsRequest.human_attribute_name(:expense6)
    td = @rms_request.expense6.to_s(:delimited) + "円"  
  tr
    th =RmsRequest.human_attribute_name(:expense7)
    td = @rms_request.expense7.to_s(:delimited)  + "円"       
  tr
    th =RmsRequest.human_attribute_name(:expense8)
    td = @rms_request.expense8.to_s(:delimited)  + "円"       
  tr
    th =RmsRequest.human_attribute_name(:expense9)
    td = @rms_request.expense9.to_s(:delimited)  + "円"                                         
  tr
    th =RmsRequest.human_attribute_name(:expense10)
    td = @rms_request.expense10.to_s(:delimited)  + "円"
  tr
    th =RmsRequest.human_attribute_name(:content)
    td = raw common_convert_nbsp(auto_link(simple_format(h(@rms_request.content), {}, sanitize: false, wrapper_tag: "p")))
  tr
    th =RmsRequest.human_attribute_name(:remarks)
    td = raw common_convert_nbsp(auto_link(simple_format(h(@rms_request.remarks), {}, sanitize: false, wrapper_tag: "p")))    

br

div
  div.float-right
    span = link_to '編集', edit_rms_request_path(@rms_request), class: 'btn btn-primary' 
    span = raw "&nbsp;&nbsp;&nbsp;"
    - days = @rms_request.yyyy.to_s + "年" + sprintf("%02d月",@rms_request.mm) + sprintf("%02d日",@rms_request.dd)
    span = link_to '削除', @rms_request, data: { confirm: "\n#{days}\n#{@rms_request.title}\nのご依頼を削除します。よろしいですか？" }, method: :delete, class: 'btn btn-danger'      
  div.float-left
    = raw '<a href="#" onClick="history.back(); return false;">戻る</a>'
div.clearfix  

p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("ご依頼", rms_requests_path)     
    li.breadcrumb-item.active aria-current="page" = '表示'
    
p    