config/routes.rb
Rails.application.routes.draw do

  root to: 'rms_main#index'
  resources :rms_requests
  resources :rms_clients 
  
  get  '/login', to: 'rms_login#new'
  post '/login', to: 'rms_login#create'
  delete '/logout', to: 'rms_login#destroy'
  
end

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    = raw '<meta charset="UTF-8">'
    =  "\n"    
    title = yield(:title) 
    =  "\n"      
    = raw '<meta name="robots" content="noindex, nofollow" />'
    =  "\n"      
    = raw '<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1" />'
    =  "\n"    
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
    
  body
  
    nav.navbar.navbar-expand-md.navbar-light.bg-primary
      .navbar-brand.text-white
        = ' ' +  t('contents.title')
         
      ul.navbar-nav.ml-auto
        - if current_user.present?
          li.nav-item= link_to 'ホーム',  root_path, class: 'nav-link',style: "color:#fff;"         
          li.nav-item= link_to '顧客',  rms_clients_path, class: 'nav-link',style: "color:#fff;"             
          li.nav-item= link_to 'ご依頼',  rms_requests_path, class: 'nav-link',style: "color:#fff;"
          li.nav-item= link_to 'ログアウト',  logout_path, class: 'nav-link',style: "color:#fff;", method: :delete       
    .container
      - if flash.notice.present?
        .alert.alert-success id="msg_notice" = flash.notice
      - if flash.alert.present?
        .alert.alert-danger id="msg_alert"= flash.alert  
                 
      = yield
    
      br
    
      nav.container.bg-primary.p-2.text-center
        .text-center.text-white = "Request Management System"
        .text-center.text-white = "Copyright 2019 Takeshi Okamoto All Rights Reserved."  